### PR TITLE
num-windows, batteries-windows, and menhir-windows

### PR DESCRIPTION
**Pull request by qnighy**
Especially, `sexplib-windows` now needs a (non-dummy) `num-windows` package.

### CODE REVIEW

**Comment by whitequark** [comment]
Can you please rebase, and squash commits fixing the newly introduced packages?

**Comment by qnighy** [comment]
@whitequark sure, rebased!

**Comment by whitequark** [comment]
@qnighy by the way, in recognition of your high-quality PRs I gave you write access to this repository.

**Comment by qnighy** [comment]
@whitequark thank you! These PRs are by-products of cross-compiling [SATySFi](https://github.com/gfngfn/SATySFi) and I will also prepare PRs for adding [`core_kernel-windows` and `ppx_deriving-windows`](https://github.com/qnighy/satysfi-cross-windows/tree/a557ca34fa821844edafb238181299d6b3f05388/opam-aux).

**Comment by whitequark** [comment]
Ah, one nit for the future--instead of `Remove base-num-windows and num-windows.0.` I would write `-base-num-windows.0 -num-windows.0`.

**Pull request merged**
