### PR TITLE
Add yojson.2.2.2, yojson-five.2.2.2

### PR DESCRIPTION
**Pull request by WardBrian**
Didn't have a chance to test locally so I'm hoping these pass CI

### CODE REVIEW

**Comment by WardBrian** [comment]
Current failures look unrelated to my changes

**Comment by WardBrian** [comment]
@toots this is failing with

```
#=== ERROR while compiling conf-gcc-windows64.1 ===============================#
# context              2.1.5 | linux/x86_64 | ocaml-base-compiler.4.14.1 | file:///home/opam/opam-cross-windows
# path                 ~/.opam/4.14.1/.opam-switch/build/conf-gcc-windows64.1
# command              /usr/bin/sh -exc ${TOOLPREF64-x86_64-w64-mingw32-}gcc --version
# exit-code            127
# env-file             ~/.opam/log/conf-gcc-windows64-234-9489c4.env
# output-file          ~/.opam/log/conf-gcc-windows64-234-9489c4.out
### output ###
# + x86_64-w64-mingw32-gcc --version
# /usr/bin/sh: 1: x86_64-w64-mingw32-gcc: not found
```

Any ideas?

**Comment by toots** [comment]
Yes, the image is rebuilding the base compiler and some of the expected env variables to be able to locate the cross-compiler are not set.

I'll look at it as soon as time allows. Meanwhile I'm happy to give you more access if you want to have a look too. Basically, one of two things need to happen (both would be even better)
* The base image for the tests needs to be rebuilt and pushed to docker
* The test script needs to be updated to include the proper env variable in case it needs to rebuild during the test in the future.

**Comment by WardBrian** [comment]
@toots looks like I unblocked CI

I think rebuilding the docker image would still be worthwhile from a speed perspective

**Comment by toots** [comment]
Thanks!

**Pull request merged**
