### PR TITLE
Add findlib (libraries only) and ppx_deriving.5.2

### PR DESCRIPTION
**Pull request by WardBrian**
This PR adds the library components of `ocamlfind` (`findlib`) and an updated version of `ppx_deriving`

------
### Historical problems:

I'm having difficulty due to the use of `findlib.dynload` in this package. If I compile with the basic `dune build -x windows`, I get

```
# Error: The file /home/brian/.opam/win11/windows-sysroot/lib/findlib/findlib_dynload.cmxa is not a compilation unit description
```

I tried `OCAMLFIND_TOOLCHAIN=windows dune build -x windows`. This seems to work a little better, but when it is time to actually run the `ppx.exe` executable it fails with

```
bash: ../default/.ppx/0224ad3443a846e54f1637fccb074e7d/ppx.exe: cannot execute binary file: Exec format error
```

This sounds related to https://github.com/ocaml/dune/issues/3698 but I've experienced it on 3 different dune versions including 2.8.4 and 2.9.1

Any wisdom to share @toots? Thanks again for all your help as I learn my way around this

### CODE REVIEW

**Comment by toots** [comment]
Looks like a similar issue indeed. No test were ever added for regression and it already happened once so it's possible it's happening again. 

Any chance you could try dune `1.11`? I believe this one works but it's pretty old now.

**Comment by WardBrian** [comment]
This package depends on ppxlib >= 20. In #208, the ppxlib I supplied is 22.2 (a couple other packages like base need ppxlib >= 22), which requires dune >= 2.7. It's a bit of a mess out there

**Comment by WardBrian** [comment]
The CI for this actually does depend on #208 being merged, which I hadn't noticed. Whoops

**Comment by WardBrian** [comment]
No, there's a message saying "only project collaborators" can merge

**Comment by WardBrian** [comment]
The [error in CI](https://github.com/ocaml-cross/opam-cross-windows/runs/4081386264?check_suite_focus=true) now matches what I've been getting locally

**Comment by WardBrian** [comment]
Yeah @toots I'm pretty stuck on this one. Do you know for certain which dune version(s) > 2 should work?

**Comment by WardBrian** [comment]
Running in the CI instance without `OCAMLFIND_TOOLCHAIN` yields a third, slightly different error:


```
# (cd _build/default.windows && /home/opam/.opam/4.12.0/windows-sysroot/bin/ocamlopt -w -40 -w -27-9 -g -o src/ppx_deriving_main.exe -linkall /home/opam/.opam/4.12.0/windows-sysroot/lib/ocaml/compiler-libs/ocamlcommon.cmxa /home/opam/.opam/4.12.0/windows-sysroot/lib/ocaml-compiler-libs/common/ocaml_common.cmxa /home/opam/.opam/4.12.0/windows-sysroot/lib/ocaml-compiler-libs/shadow/ocaml_shadow.c[...]
# File "_none_", line 1:
# Error: Files /home/opam/.opam/4.12.0/windows-sysroot/lib/findlib/findlib.cmxa
#        and /home/opam/.opam/4.12.0/windows-sysroot/lib/ocaml/stdlib.cmxa
#        make inconsistent assumptions over implementation Stdlib__sys
```

Any guesses on this @toots?

I checked and your patch to dune is still in the repo ATM, so it should be in the two most recent releases at least

**Comment by WardBrian** [comment]
@toots do you think this will require the existence of ocamlfind-windows?

**Comment by toots** [comment]
I would recommend to do a verbose `dune` build, catch the step that is failing, inspect the binary that is executed and confirm that it is built for the wrong platform.

At this point, you can either submit a ticket to `dune` or investigate further and directly submit a patch.

If it's the same issue, let's make a test for it this time haha. Might need help from them, I couldn't figure it out last time.

**Comment by toots** [comment]
Ha just reading further. This inconsistency is weird. Maybe do a verbose build and post the log here?

**Comment by WardBrian** [comment]
Here is the CI output with `--verbose`:

https://gist.github.com/WardBrian/1375f4eacf7ef04d7aba02f178527a45

Local machine:

https://gist.github.com/WardBrian/04e9c2114817bea10b70b6a6fff7f531

**Comment by toots** [comment]
Are you familiar with `docker`? I'm concerned about the docker issue first, it might indicate an underlying problem with the `ocaml-windows` package.

I'd suggest to do a `docker run -t -i --entrypoint /bin/bash <id>` where `id` is the `id` of the docker layer right before the error, run the command manually inside it and inspect `/home/opam/.opam/4.12.0/windows-sysroot/lib/findlib/findlib.cmxa` and `/home/opam/.opam/4.12.0/windows-sysroot/lib/ocaml/stdlib.cmxa` to see what's the difference between them.

**Comment by WardBrian** [comment]
I'm not terribly adept at using docker - in particular, I'm not sure how to find the layer ID you describe

**Comment by WardBrian** [comment]
Okay I've figured out how to get into the docker image and recreate the error. Not sure how to inspect the `.cmxa` files as they're binary files

**Comment by toots** [comment]
Great! `ocamlobjinfo` should give you some info.

**Comment by WardBrian** [comment]
Here's the dump:

https://gist.github.com/WardBrian/97d80055e863bb894ed9f075fe9c7203

Based on the hashes alone the problem seems to be that `Findlib` is importing the Stdlib__sys implementation in `$OPAM/lib/ocaml`, not `$OPAM/windows-sysroot/lib/ocaml`.

Seems like a pretty big problem, but I am not sure how to fix it

**Comment by WardBrian** [comment]
Do we need a `findlib-windows`-type package?

**Comment by WardBrian** [comment]
Do any other packages in the cross-windows repo use findlib.dynload (to your knowledge) @toots?

**Comment by toots** [comment]
Hi! Sorry I'm a little out of pocket at the moment, didn't have much time to look at it.

The general idea is that everything in `$OPAM/windows-sysroot/lib/ocaml/` should be compiled for the windows cross-compiler and, in particular, it should be windows binary code. `ocamlobjinfo` seems to point to an issue where `findlib` compiles and installs stuff in that directory that is meant for the host library, at `$OPAM/lib/ocaml`.

Another thing to think of is _binaries_ vs. _libraries_. All binaries should be built for the host that is doing the cross-compiling so they can be executed on the host. Thus, `findlib` as a _binary_ should be the host `findlib` (and it should install its libraries in `$OPAM/lib/ocaml`). You might consider adding a `findlib-windows` only if some cross-compiled packages require the findlib _libraries_.

Hope that clarifies things a bit.

**Comment by WardBrian** [comment]
Yes, this package requires [findlib.dynload as a library](https://github.com/ocaml-ppx/ppx_deriving/blob/0a89b619f94cbbfc3b0fb3255ab4fe5bc77d32d6/src/dune#L8)

I'm not sure if any other packages currently do. I suspect not, because the issue with the findlib in `$OPAM/windows-sysroot/lib`  using the host OCaml libraries exists even if you make a switch on OCaml 4.07.0 and install ocaml-windows.4.07.0

**Comment by WardBrian** [comment]
Hi @toots - this is building now. I've added a `ocamlfind-windows` package which only builds `findlib` (not the ocamlfind executable). It should only be necessary when packages link against the runtime library of findlib

**Comment by toots** [comment]
Thanks!

**Comment by WardBrian** [comment]
Thank you @toots! You've been a massive help on all this

**Comment by toots** [comment]
Happy to! We need more 👀 on this, happy to promote you as part of the repo contributors at some point!

**Pull request merged**
