### PR TITLE
Switch back to mainstream jbuilder.

### PR DESCRIPTION
**Pull request by toots**

### CODE REVIEW

**Comment by whitequark** [comment]
```
#=== ERROR while installing ppx_ast-windows.v0.10.0 ===========================#
# opam-version         1.2.2
# os                   linux
# command              jbuilder build -p ppx_ast -j 4 -x windows
# path                 /home/opam/.opam/4.06.1/build/ppx_ast-windows.v0.10.0
# compiler             4.06.1
# exit-code            1
# env-file             /home/opam/.opam/4.06.1/build/ppx_ast-windows.v0.10.0/ppx_ast-windows-8-4d7b56.env
# stdout-file          /home/opam/.opam/4.06.1/build/ppx_ast-windows.v0.10.0/ppx_ast-windows-8-4d7b56.out
# stderr-file          /home/opam/.opam/4.06.1/build/ppx_ast-windows.v0.10.0/ppx_ast-windows-8-4d7b56.err
### stderr ###
#         bash src/location_helper.ml [default.windows] (exit 1)
# (cd _build/default.windows/src && /bin/bash -e -u -o pipefail -c '../generate/select.exe location_helper.ml-4.06 location_helper.ml-default > location_helper.ml')
# /bin/bash: ../generate/select.exe: No such file or directory
```

**Comment by toots** [comment]
I know. Clearly, one binary isn't built as it should but I have no time to investigate right now. It could be either a mistake in upstream's packaging or a bug in `jbuilder`.

**Comment by whitequark** [comment]
Well, the only result of switching to mainstream jbuilder is that now some packages are broken with no workaround available. Then we shouldn't switch.

**Comment by toots** [comment]
Not to be snarky but I'm not a big fan of this rigid workflow. The reason flexible workflows such as agile were invented for software engineering purposes is precisely because it works better to break things down into smaller bits and incrementally ship updates. Monolithic workflows just don't work well with software development.

While we're discussing this, things are moving by smaller incremental bits. As it stands, `ppx_ast`, the single package at fault is already obsolete. Merging this PR would make it very easy to simply update the `ppx` packages and remove the faulty one. However, neither do I want to mix this work with this PR nor get started on it while `jbuilder-windows` is still the main builder.

**Comment by whitequark** [comment]
> Not to be snarky but I'm not a big fan of this rigid workflow. The reason flexible workflows such as agile were invented for software engineering purposes is precisely because it works better to break things down into smaller bits and incrementally ship updates. Monolithic workflows just don't work well with software development.

Agile is irrelevant because there's no organization and no code owners behind opam-cross repositories. As it stands, the reality of opam-cross is that it is updated by the "scratch your own itch" principle, and in this case, it is more important to have a green master at all times than to have a flexible workflow.

**Comment by toots** [comment]
Which precisely doesn't cut it for repository-wide changes such as this one. That's a typical case that requires more coordination, thus more flexibility than just updating a couple of packages.

Anyway, I've brought back `jbuilder-windows` for that one package and that seems to have solved it. We should merge and get rid of it right after if so.

**Comment by toots** [comment]
Gmpf

**Comment by toots** [comment]
Hi,
It seems that we have a fundamental disagreement here. Frankly, I don't think that I have time to argue about all this at the moment. I'm gonna fork away and keep working from there. I'm still very much open to collaborating here and merge back, though.

**Pull request closed without merging**
