### PR TITLE
ocaml-windows 4.06.1

### PR DESCRIPTION
**Pull request by qnighy**
I wanted this to build a software which requires `ocaml >= 4.05.0`. I'm not sure if this repository is ready to accept this kind of patch...

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks! At first glance, this looks very good. How did you update the `m.h`/`s.h`/`Makefile.in` files?

**Comment by qnighy** [comment]
I just `git diff 4.04.0 4.06.1`ed on `ocaml` and edited them by hand. As a memorandum, one nontrivial change is that now `asmrun/Makefile(.nt)` respects `PROFILING`, thus I had to disable it.

**Comment by whitequark** [comment]
Very good! I won't be able to merge this PR right away because I need to update the Docker-based testsuite to also function on 4.06, but I don't see anything wrong with the substance of it.

Do you think you can (a) rebase on top of master, (b) remove the old flexdll and compiler (the policy of ocaml-cross repositories is to keep exactly one version of a package available), (c) update versions in README?

**Comment by qnighy** [comment]
@whitequark Sure. Should I test some packages? I've done only a minimal test (compiling hello world) by myself.

**Comment by toots** [comment]
I'll try to look at the docker part soon. Good job on this!

**Comment by whitequark** [comment]
@qnighy If you have Docker, you can run `WORLD=1 ./tests/run_tests.sh` to test every package.

**Comment by toots** [comment]
CI is being weird, gonna close and re-open.

**Comment by toots** [comment]
Yey, passed!

**Comment by toots** [comment]
I don't have much time to review the code unfortunately but this looks good on my end.

**Pull request merged**
