### PR TITLE
Upgrade ppx-related packages in preparation for OCaml 4.06.1.

### PR DESCRIPTION
**Pull request by qnighy**
In preparation for #70. `v0.9` of these packages have upper bound on OCaml version.

### CODE REVIEW

**Comment by qnighy** [comment]
> We always build `num` and other base packages on Windows, so there shouldn't be base-num-windows and similar packages in this repository.

My understanding is that `num` is removed from `ocaml >= 4.06.0`, and

- `base-num` is a dummy package that just requests `ocaml < 4.06.0`
- `num.0` is a dummy package that just requests `base-num`
- `num.1.1` is a real package (which spun off from `ocaml`) which is only provided under `ocaml >= 4.06.0`.

So I propose to add `num-windows.0` for now, and add `num-windows.1.1` when we move to `ocaml-windows.4.06.1`. In fact, I already prepared `num-windows.1.1` in my local repo.

**Comment by qnighy** [comment]
And CI seems to be stalling?

**Comment by whitequark** [comment]
@qnighy regarding CI, perhaps amend the last commit and force-push? Travis seems to have odd trouble lately.

**Comment by qnighy** [comment]
@whitequark Trying to close and open the issue.

**Comment by qnighy** [comment]
> The job exceeded the maximum time limit for jobs, and has been terminated.

Oops.

**Comment by qnighy** [comment]
Passed.

**Comment by whitequark** [comment]
Thanks for this excellent PR!

**Pull request merged**
