### PR TITLE
Added x86 tests, fix ocaml-windows32

### PR DESCRIPTION
**Pull request by toots**
This makes tests available in both architecture. Surprise, there was a bug in `ocaml-windows32`.. 

I'm not sure about switching CI to run on both arch, though, it's already timing out a lot on one only..

### CODE REVIEW

**Comment by hcarty** [comment]
I don't know how simple/awful it would be to use, but https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/ looks like it could be useful in this context.

**Comment by toots** [comment]
It seems pretty easy to setup indeed: https://github.com/toots/opam-cross-windows/commit/d9c8c3e722a35e3a5dc43c3eef22e1ca0c08eea5

I'm not a fan of microsoft taking over github, nor the fact that the pipeline asks for write access but unlimited CI minutes is indeed appealing, specially if that allows us to cover both arch. I'll let @whitequark decide what he prefers.

**Comment by whitequark** [comment]
> I'm not a fan of microsoft taking over github, nor the fact that the pipeline asks for write access but unlimited CI minutes is indeed appealing, specially if that allows us to cover both arch. I'll let @whitequark decide what he prefers.

I'm OK with it. (Also, she.)

**Comment by toots** [comment]
Ok, I've added the azure pipeline config and removed the travis one. The tests pass on my own account:

screenshot 2018-09-13 13 40 22

I don't think that I have the access to setup and switch this repository so this is as far as I can get 🙂

**Comment by whitequark** [comment]
How do I configure it?

**Comment by toots** [comment]
I started from here: https://github.com/marketplace/azure-pipelines It guides you all the way to the azure dev console. I haven't looked at how to hook it up with the repo here, though I believe it should be easy. I also don't know about public access. It'd be nice if anyone could check the build logs and perhaps restart a build.

**Comment by whitequark** [comment]
@toots Sorry for the delay. I think you're being a great steward of opam-cross-windows and I've added you as a repo admin. You can now perform CI changes as well as merge with status override.

**Comment by jeremyepling** [comment]
I'm a product manager on the Azure Pipelines team. Let me know if you have any questions or suggestions.

**Comment by whitequark** [comment]
@toots I think I've set up Azure Pipelines for the organization, let me know if something else doesn't work.

**Comment by toots** [comment]
Unfortunately, I still cannot see the repo when logged in the Azure DevOps console.

If I compare to Travis CI, in Travis CI I can edit settings for the `opam-cross-windows` repository of the `ocaml-cross` organization. In the Azure console, I can only setup repositories from orgs for which I have admin access.

Even though, I'm not sure if I can setup the CI build under any king of `ocaml-cross` umbrella. When trying with `savonet/liquidsoap`, it still creates a pipeline under my own account, which is not optimal.

Once this is setup, the next step would be to use it in the branch protection rules for `master`:
screenshot 2018-09-15 19 40 15

Maybe @jeremyepling can provide more directions 🙂

**Comment by jeremyepling** [comment]
Azure Pipelines has it's own concept of an organization and project, separate from GitHub. It's common to name your Azure Pipelines organization and project the same as your GitHub organization and repository. The Azure Pipelines org was created when you installed the Azure Pipelines app into the ocalm-cross org. After that, you should have go through a wizard to select the repos you want to build and commit the azure-pipelines.yml to this repo. It looks like that was done based on [commit 8afa1a2](https://github.com/ocaml-cross/opam-cross-windows/pull/84/commits/8afa1a2aa4ebd753b2eb565c8390b8ca94181332).

@toots can you send me a link to the build results you shared in the screenshot above? That should work as long as the Azure Pipelines project is public. That should be the default, but if it isn't you can [change it](https://docs.microsoft.com/en-us/azure/devops/organizations/public/make-project-public?view=vsts&tabs=new-nav).

The Azure Pipelines experience doesn't show your GitHub repositories. It just shows the build pipelines you have setup, which are - by default - named after your repository.

**Comment by toots** [comment]
Thanks for the explanations @jeremyepling. I think that the discrepancy here is that I have write access to this repo but I am not an admin on the github organization.

I have tried to create a mirroring `ocaml-cross` organization on the azure dev platform but I cannot link the repository. Here's what I see when I try:

screenshot 2018-09-17 14 54 34

It only shows my own fork of the repository, which where the commit your pointed out is coming from.

Let me know if you have more info to help us set this up!

**Comment by whitequark** [comment]
@toots (I haven't forgot about this and will figure things out shortly.)

**Comment by toots** [comment]
I think this should be merged. I'll temporarily remove the azure config for now and merge.

**Pull request merged**
