### PR TITLE
ppx, cohttp and angstrom

### PR DESCRIPTION
**Pull request by hcarty**
The brings in cohttp and its dependencies which include lots of ppx.  angstrom is also along for the ride.

I'll clean up the commits themselves once the general approach is vetted.  That cleanup will include splitting out the multi-package-affecting commits into per-package commits with appropriate commit messages.

@whitequark Do you have any suggestions for better ppx handling?  This approach (install parallel versions under `windows-sysroot`) seems like a hack.  But I'm not sure how to make a better hack with the tools we have available.

Some general notes:
- ppx_blob and ppx_defer: easy to port over and useful in my code; not required for cohttp
- angstrom: useful in my code and easy to port since cstruct was already required for cohttp
- Everything else is required for cohttp
- ppx_deriving is version 3.3 because of Jane St ppx version constraints.  It's really only providing its runtime library in this package.

### CODE REVIEW

**Comment by whitequark** [comment]
How about this idea. The ppx cross-package is built exactly like usual and then the ppx executable is replaced with a symlink to the executable for the build system.

**Comment by hcarty** [comment]
I'd tried that initially and ran into a bunch of problems.  It's been long enough though that I don't remember the details though.

I'm more familiar with the whole setup now so I'll try the symlink approach again, hopefully some time in the next week, and come back with the results.

**Comment by whitequark** [comment]
Closing this PR as stale since the PPX cross-compilation stuff was completely reworked by @toots. Feel free to reopen!

**Comment by hcarty** [comment]
👍 I'll hopefully get a chance to come back to this. It'll probably be a few months though.

**Pull request closed without merging**
