### PR TITLE
OCaml 4.07.0

### PR DESCRIPTION
**Pull request by toots**
I still have to run the tests on it but it seems to be working great. One problem tho: there's no `4.07.0+32bit` `opam` switch at the moment..

### CODE REVIEW

**Comment by whitequark** [comment]
Do you think you could add the 32bit switch? The opam package repository has a lot of commits authored by me adding this switch for earlier versions of ocaml, you could take a look at those for inspiration.

**Comment by toots** [comment]
`4.07.0+32bit` switch has been merged & spacetime compilation fixed. I think that this is good to go!

**Comment by toots** [comment]
Ping?

**Comment by whitequark** [comment]
Sorry, I never got the notification from GitHub.

**Comment by toots** [comment]
Thks!

**Pull request merged**
