### PR TITLE
md5sum of jbuilder-windows.1.0+beta16 has changed

### PR DESCRIPTION
**Pull request by pirbo**
I've realised it through https://travis-ci.org/Kappa-Dev/KaSim/jobs/337768157.

I have not idea of why it happened so maybe there is something deeper and this patch isn't the solution...

### CODE REVIEW

**Comment by whitequark** [comment]
How is that even *possible*? It links directly to a sha1.

**Comment by toots** [comment]
I think source folder zips are generated on the fly by GitHub. If for some
reason it is deleted, like if a cached version expire, then it's totally
possible that another one would be generated, possibly with a different md5
sum..

**Comment by OvermindDL1** [comment]
> I think source folder zips are generated on the fly by GitHub. If for some
reason it is deleted, like if a cached version expire, then it's totally
possible that another one would be generated, possibly with a different md5
sum..

This is partially correct.

Specifically source folder zips are created on the fly, however the hash can change if they change their algorithm to compress better, which they do on occasion.  They make it very clear in a few areas not to relay on hashes of source downloads, that is what 'release's are for (those are stored permanently and never changed or updated), if a source download is wanted then `git` itself should be used.

**Comment by OvermindDL1** [comment]
By releases, I mean the things at:  https://github.com/diml/dune/releases

Right now it is using things from `https://github.com/diml/dune/archives`, which is not at all correct.

**Comment by OvermindDL1** [comment]
I've never yet gone through the build system here so I'd be afraid I'd potentially miss something...  ^.^;

**Comment by toots** [comment]
That's what the CI should be for!

**Comment by whitequark** [comment]
> Specifically source folder zips are created on the fly, however the hash can change if they change their algorithm to compress better, which they do on occasion. They make it very clear in a few areas not to rely on hashes of source downloads, that is what 'release's are for (those are stored permanently and never changed or updated), if a source download is wanted then git itself should be used.

Well that means like half of opam-repository will be broken every time they "improve" the algorithm.

**Comment by OvermindDL1** [comment]
> Well that means like half of opam-repository will be broken every time they "improve" the algorithm.

Thankfully it happens very *very* rarely, but it has happened twice before that I know of in github's history (a couple months ago most recently).  But yeah, the `archive` downloads are not meant to be used for that, `release` downloads are and those are the only things that should be used in such a way, otherwise using git itself and grabbing a specific commit.  :-)

I think this most recent 'change' only caused a hash change on archives that included any files whatsoever that had a space in their name or a path that exceeded something like 100 or 120 characters or so, if no space anywhere in any names and no path exceeded that prior value then no hash update should have occurred ('should').

**Pull request merged**
