### PR TITLE
Add ao depext after PR was accepted upstream.

### PR DESCRIPTION
**Pull request by toots**
This might need a refresh of the docker images to pass test, though.

### CODE REVIEW

**Comment by whitequark** [comment]
```
make: *** No rule to make target 'ao'.  Stop.
```

**Comment by toots** [comment]
Yeah, this needs an update of the docker image. Will look into it.

**Comment by toots** [comment]
Yeah, I've tried several options but to no avail. Updating the whole `mxe` repository in the `base` image fails when building `gcc` and hand-picking `libao.mk` fails because the format has changed too much. I think we're stuck with waiting for an upstream docker image update.

**Comment by toots** [comment]
Looks like it's good to go here. Anyone care reviewing/greenlighting it?

**Pull request merged**
