### PR TITLE
Update core_kernel and dependencies 

### PR DESCRIPTION
**Pull request by WardBrian**
Similar to #207, this compiles locally but the docker instance has unrelated issues and fails before testing starts.

My apologies for all the changes at once, I didn't realize just how deep the dependency trees went. I'm happy to split it up if desired, the end goal was simply to update core_kernel to `0.14.2`

### CODE REVIEW

**Comment by WardBrian** [comment]
Sorry about the missed dep. I think it will work this time (It got through installing the really big dependency-havers before failing the first time)

**Comment by WardBrian** [comment]
I think I can run the CI locally now so I'm trying that before pushing the fix - there are a few other brand-new packages in this PR that I want to make sure I found all the dependencies for

**Comment by WardBrian** [comment]
This now passes everything locally for me in the docker instance.

**Comment by WardBrian** [comment]
It seems like the 6 hour time limit cut off the x64 test _right_ before it was going to finish. Do I need to split this PR?

**Review by toots — APPROVED** [review]
It passed one of the two architectures, I believe that this is enough. Thanks for the hard work!

**Pull request merged**
