### PR TITLE
Batch update

### PR DESCRIPTION
**Pull request by toots**
Should be a good one:
- Fix in `ocaml-windows{32,64}` build when some modules folders don't exist
- Switch to mainstream `dune`/`jbuilder`
- PPX update to new `ppxlib` and versions. Paves the way to `4.07.0`
- Some savonet package updates
- Minor tweaks to the testing system

### CODE REVIEW

**Comment by whitequark** [comment]
Thanks a lot for your work!

**Comment by toots** [comment]
The tests have timed out. Gonna run them locally and report.

**Comment by toots** [comment]
Succes!
```
% ./tests/run_tests.sh
Building pretest image..[ok]✅

From https://github.com/toots/opam-cross-windows
 * branch            master     -> FETCH_HEAD

Building atd-windows.1.12.0.. [ok]✅
Building atdgen-windows.1.12.0.. [ok]✅
Building base-windows.v0.11.1.. [ok]✅
Building base64-windows.2.2.0.. [ok]✅
Building bin_prot-windows.v0.11.0.. [ok]✅
Building biniou-windows.1.2.0.. [ok]✅
Building camomile-windows.1.0.1.. [ok]✅
Building configurator-windows.v0.11.0.. [ok]✅
Building cry-windows.0.6.2.. [ok]✅
Building dtools-windows.0.4.0.. [ok]✅
Building duppy-windows.0.7.2.. [ok]✅
Building easy-format-windows.1.3.1.. [ok]✅
Building faad-windows.0.4.0.. [ok]✅
Building fieldslib-windows.v0.11.0.. [ok]✅
Building lwt-windows.3.2.1.. [ok]✅
Building lwt_react-windows.1.1.1.. [ok]✅
Building magic-mime-windows.1.1.0.. [ok]✅
Building mm-windows.0.4.0.. [ok]✅
Building ocaml-compiler-libs-windows.v0.11.0.. [ok]✅
Building ocaml-migrate-parsetree-windows.1.0.11.. [ok]✅
Building ocaml-windows32.4.06.1.. [skipped]⚠️
Building ocaml-windows64.4.06.1.. [skipped]⚠️
Building octavius-windows.1.2.0.. [ok]✅
Building pcre-windows.7.3.4.. [ok]✅
Building ppx_assert-windows.v0.11.0.. [ok]✅
Building ppx_base-windows.v0.11.0.. [ok]✅
Building ppx_bench-windows.v0.11.0.. [ok]✅
Building ppx_bin_prot-windows.v0.11.1.. [ok]✅
Building ppx_compare-windows.v0.11.1.. [ok]✅
Building ppx_custom_printf-windows.v0.11.0.. [ok]✅
Building ppx_derivers-windows.1.0.. [ok]✅
Building ppx_enumerate-windows.v0.11.1.. [ok]✅
Building ppx_expect-windows.v0.11.0.. [ok]✅
Building ppx_fail-windows.v0.11.0.. [ok]✅
Building ppx_fields_conv-windows.v0.11.0.. [ok]✅
Building ppx_hash-windows.v0.11.1.. [ok]✅
Building ppx_here-windows.v0.11.0.. [ok]✅
Building ppx_inline_test-windows.v0.11.0.. [ok]✅
Building ppx_jane-windows.v0.11.0.. [ok]✅
Building ppx_js_style-windows.v0.11.0.. [ok]✅
Building ppx_let-windows.v0.11.0.. [ok]✅
Building ppx_optcomp-windows.v0.11.0.. [ok]✅
Building ppx_optional-windows.v0.11.0.. [ok]✅
Building ppx_pipebang-windows.v0.11.0.. [ok]✅
Building ppx_sexp_conv-windows.v0.11.2.. [ok]✅
Building ppx_sexp_message-windows.v0.11.0.. [ok]✅
Building ppx_sexp_value-windows.v0.11.0.. [ok]✅
Building ppx_typerep_conv-windows.v0.11.1.. [ok]✅
Building ppx_variants_conv-windows.v0.11.1.. [ok]✅
Building ppxlib-windows.0.3.0.. [ok]✅
Building re-windows.1.8.0.. [ok]✅
Building react-windows.1.2.1.. [ok]✅
Building result-windows.1.3.. [ok]✅
Building seq-windows.0.1.. [ok]✅
Building sexplib0-windows.v0.11.0.. [ok]✅
Building stdio-windows.v0.11.0.. [ok]✅
Building typerep-windows.v0.11.0.. [ok]✅
Building variantslib-windows.v0.11.0.. [ok]✅
Building vorbis-windows.0.7.1.. [ok]✅
Building yojson-windows.1.4.0.. [ok]✅
```

**Comment by whitequark** [comment]
Huge thanks!

**Pull request merged**
