### PR TITLE
+core_kernel.v0.10.0 (and its dependencies)

### PR DESCRIPTION
**Pull request by qnighy**
I'm not sure about version dependencies e.g.

```
depends: [
  "base-windows"                    {>= "v0.10" & < "v0.11"}
  "bin_prot-windows"                {>= "v0.10" & < "v0.11"}
  "configurator"                    {>= "v0.10" & < "v0.11"}
  ...
]
```

Should I remove `{>= "v0.10" & < "v0.11"}` in accordance with the existing `ppx_*` packages?

### CODE REVIEW

**Comment by qnighy** [comment]
Since the PR is too long for CI, I've split part of it into #75.

**Comment by whitequark** [comment]
No, these version requirements should not be removed, or there will be spurious failures while upgrading packages afterwards.

**Comment by qnighy** [comment]
@whitequark then is it good to resurrect version requirements in existing `ppx_*` packages? For example, dependencies of `ppx_metaquot-windows` are:

```
depends: [
  "ppx_core" {>= "v0.10" & < "v0.11"}
  "ppx_core-windows"
  "ppx_driver" {>= "v0.10" & < "v0.11"}
  "ppx_driver-windows"
  "ppx_traverse_builtins-windows"
  "jbuilder-windows" {build}
  "ocaml-migrate-parsetree-windows"
  "ocaml-windows"
]
```

They only have version requirements on non-`-windows` dependencies.

**Comment by whitequark** [comment]
Yes, please do that if you have some time!

**Comment by VMatthijs** [comment]
Any idea if this has been resolved? Is there currently a way of using core_kernel when cross-compiling to Windows?

**Comment by toots** [comment]
The PR looks good to me. I have to run the CI tests locally since they timeout on Travis but if they run good I'm good with it.

**Comment by toots** [comment]
hi @VMatthijs,

Unfortunately, this PR has fallen out of date. It needs to be update to the `v0.11` versions with `opam 2.0` package format. Are you in a position to do that? I'll be making sure to review and merge quickly this time if so.

**Comment by toots** [comment]
`core_kernel` has been added with version `v11`, closing this one.

**Pull request closed without merging**
